[package]
name = "dfns-cggmp21-blueprint"
version = "0.2.0"
description = "A DFNS CGGMP21 Blueprint that can run keygen and signing jobs on demand from the Tangle network"
edition = "2021"

[dependencies]
blueprint-sdk = { git = "https://github.com/tangle-network/blueprint.git", branch = "main", default-features = false, features = [
    "std",
    "tracing",
    "macros",
    "tangle",
    "networking",
    "local-store",
    "round-based-compat",
] }
hex = { version = "0.4.3", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
round-based = { version = "0.4.1", features = ["runtime-tokio", "derive"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", default-features = false, features = ["sync", "rt"] }
futures = "0.3"
crossbeam-channel = "0.5"
libp2p = { version = "0.54", default-features = false }
rand_chacha = "0.3"
sha2 = "0.10"

# MPC specific deps
cggmp21 = { version = "0.6", features = ["curve-secp256k1"] }
key-share = { version = "0.6", features = ["serde"] }

[dev-dependencies]
blueprint-sdk = { git = "https://github.com/tangle-network/blueprint.git", branch = "main", default-features = false, features = ["std", "tangle", "testing", "networking", "round-based-compat"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "test-util"] }
tracing-subscriber = "0.3"

[features]
default = ["std"]
std = []
